# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import scarlet.cms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotmodule',
            name='intro_copy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Pin title'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='order',
            field=scarlet.cms.fields.OrderField(db_index=True, default=0, verbose_name=b'Pin number'),
        ),
    ]
