# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0002_auto_20170727_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspotmodule',
            name='intro_copy',
            field=models.TextField(blank=True),
        ),
    ]
