# Generated by Django 2.2.11 on 2020-03-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video')], db_index=True, max_length=255),
        ),
    ]
